language: python
python:
  - "3.6"

install:
  - pip install -r requirements-test.txt
  - python setup.py install
  - sudo apt-get update
  - sudo apt-get install -y nginx-full php-fpm

script:
  - pytest
